# Generated by Django 4.2.10 on 2024-06-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_productz_pname_alter_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='productz',
        ),
    ]
